---
- hosts: localhost
  become: no

  vars_files:
    - "{{ env_spec }}"

  tasks:
    - name: Generate the Environment
      include_role:
        name: ar_aws_infra
      vars:
        ar_aws_infra_dest_dir: "{{ dest_dir }}"
        ar_aws_infra_key_path: "{{ key_path }}"
        ar_aws_infra_name: "{{ infra_name }}"
        ar_aws_infra_description: "{{ infra_name }}"
        ar_aws_infra_domain: "{{ infra_domain }}"
        ar_aws_infra_region: "{{ infra_region }}"
        ar_aws_infra_envs: "{{ envs }}"
        ar_aws_infra_machine_types: "{{ machine_types }}"

- import_playbook: gen-ansible-inventory.yml
- import_playbook: rhel-subscribe.yml
