---
- hosts: localhost
  become: no

  vars_files:
    - "{{ env_spec }}"

  tasks:
    - debug:
        msg: "Entering gen-ansible-inventory.yml"

    - name: Get inventory details
      include_role:
        name: ar_aws_infra
        tasks_from: get-inventory
      vars:
        ar_aws_infra_dest_dir: "{{ dest_dir }}"

    - name: Ensure ssh client config present
      include_role:
        name: ar_ssh_config
      vars:
        ar_ssh_config_name: "{{ infra_name }}"
        ar_ssh_config_machines: "{{ ar_aws_infra_all_machines }}"
        ar_ssh_config_public_user: "{{ public_host_user }}"

    - name: Create ansible inventory
      include_role:
        name: ar_inv_hostname
      vars:
        ar_inv_hostname_dest_dir: "{{ dest_dir }}/inventory"
        ar_inv_hostname_machines: "{{ ar_aws_infra_all_machines }}"

