---
#
# Generate the ansible inventory at <dest-dir>/inventory/hosts
# For the ansible inventory, server hostnames are processed using a '-' delimiter and associated groups are defined, e.g
# dc1-os-node-1 would result in the following groups:
#   - dc1             Contains all hosts with 'dc1'
#   - dc1_os          Contains all hosts with 'dc1-os'
#   - dc1_os_node     Contains all hosts with 'dc1-os-node'
#   - dc1_os_node_1   Contains only the host 'dc1-os-node-1'
#

- hosts: localhost
  become: no

  vars_files:
    - "{{ env_spec }}"

  tasks:
    - debug:
        msg: "Entering gen-ansible-inventory.yml"

    - ec2_instance_facts:
        filters:
          "tag:InfraName": "{{ infra_name }}"
          instance-state-name: [ "running", "shutting-down", "stopping", "stopped" ]
      register: ec2_instances

    - name: Ensure generated dirs exist
      file:
        dest: "{{ dest_dir }}/inventory/group_vars"
        state: directory

    - name: "create inventory file"
      copy:
        content: "{{ ec2_instances | json_query('instances[*].tags.Name') | os_ansible_inventory }}"
        dest: "{{ dest_dir }}/inventory/hosts"

    - name: "create ansible global vars"
      template:
        src: ../templates/os-ansible-globals.j2
        dest: "{{ dest_dir }}/inventory/group_vars/all"

    - name: Refresh inventory to ensure seed hosts changes picked up
      meta: refresh_inventory

    - name: Clear facts to ensure seed hosts changes picked up
      meta: clear_facts

    - name: reload facts
      setup:

    - name: Load new group_vars
      include_vars:
        file: "{{ dest_dir }}/inventory/group_vars/all"
