---
- hosts: localhost
  become: no

  vars:
    template_dir: ../templates

  vars_files:
    - "{{ env_spec }}"

  tasks:
    - debug:
        msg: "Entering genterra-main.yml"

    - name: "Ensure dir exists: {{ dest_dir }}"
      file:
        path: "{{ dest_dir }}"
        state: directory

    - name: "Generate the terraform main script"
      template:
        src:  "{{ template_dir }}/{{ terraform_template }}"
        dest: "{{ dest_dir }}/main.tf"

    - name: "Generate the terraform variables definition"
      template:
        src:  "{{ template_dir }}/{{ terraform_variables }}"
        dest: "{{ dest_dir }}/variables.tf"

    - name: "Generate the terraform outputs definition"
      template:
        src:  "{{ template_dir }}/{{ terraform_outputs }}"
        dest: "{{ dest_dir }}/outputs.tf"

    - name: "Generate the terraform exposed variables template"
      template:
        src:  "{{ template_dir }}/{{ terraform_out_vars }}"
        dest: "{{ dest_dir }}/terraform_exposed_vars.yml.tpl"
