---
- hosts: localhost
  become: no

  vars:
    template_dir: ../templates

  vars_files:
    - "{{ env_spec }}"

  tasks:
    - debug:
        msg: "Entering genterra-secrets.yml"

    - name: Ensure vault dir exsits
      file:
        path: "{{ dest_dir }}/vaults"
        state: directory
        mode: 0700

    - name: check if terraform_secret_vars.yml file exists
      stat:
        path: "{{ dest_dir }}/terraform_secret_vars.yml"
      register: terraform_vars

    - name: Create tmp secret
      copy:
        dest: "{{ dest_dir }}/vaults/.secret"
        content: "{{ infra_secret_passphrase }}"
        mode: 0600
      when: terraform_vars.stat.exists

    - name: Create the vault
      shell: "ansible-vault encrypt {{ dest_dir }}/terraform_secret_vars.yml \
                --vault-password-file={{ dest_dir }}/vaults/.secret \
                --output={{ dest_dir }}/vaults/infra-secrets.vault"
      when: terraform_vars.stat.exists

    - name: Remove secret
      file:
        path: "{{ dest_dir }}/vaults/.secret"
        state: absent
      when: terraform_vars.stat.exists

    - name: Remove terraform secrets
      file:
        path: "{{ dest_dir }}/terraform_secret_vars.yml"
        state: absent
      when: terraform_vars.stat.exists
