# Deprecated in favour of direct queries on ec2_instance_facts result object (instance_res below)
#
# Translates groups into lists of aws instance_id strings
# 'target' must be specified and must be set to either an ansible group, list of ansible groups or the word 'all'
# Whilst 'all' is an ansible group, this ignores that and establishes all the machines that are running in aws instead.
# This covers the case where the local ansible inventory has become out of date.
# See gen-ansible-inventory.yml for details on what ansible groups are created
#

- ec2_instance_facts: # Can supply a filter here but I'm being lazy!
    filters:
      instance-state-name: [ "pending", "running", "shutting-down", "stopping", "stopped" ]
  register: instance_res

- name: "Get all aws instances"
  set_fact:
    all_instances: "{{ instance_res | json_query('instances[*].[instance_id, tags.Name]') }}"

- assert:
    that:
      - "target | length > 0"

- name: "Clear server group if target is 'all'"
  set_fact:
    server_list: null
  when: "target is string and target == 'all'"

- name: "Set server group if target is not 'all'"
  set_fact:
    server_list: "{{ groups[target] }}"
  when: "target is string and target != 'all'"

- name: "Initialise tmp server group list"
  set_fact:
    tmp_server_list: []
  when: "target is not string"

- name: "Build server group list if target is a list"
  set_fact:
    tmp_server_list: "{{ tmp_server_list }} + [ {{ groups[item] }} ]"
  when: "target is not string"
  with_items: "{{ target }}"

- name: "Set server group list if target is a list"
  set_fact:
    server_list: "{{ tmp_server_list | flatten }}"
  when: "target is not string"

- name: "Show server_list"
  debug: var=server_list

- name: "Establish targets"
  set_fact:
    targets: "{{ all_instances | aws_instance_array_to_array_of_dicts(server_list) }}"

- name: "Set instance ids"
  set_fact:
    target_instance_ids: "{{ targets | json_query('[*].instance_id') }}"

- name: "Get ec2 instance facts"
  ec2_instance_facts:
    instance_ids: "{{ target_instance_ids }}"
  register: target_ec2_instance_facts

- name: "Show target machines"
  debug: var=targets verbosity=0

- name: "Show target machine facts"
  debug: var=target_ec2_instance_facts verbosity=1
